import Parser from 'rss-parser';
import type { Article, Domain, NewsPayload, Region, SourceStatus } from './types';
import { dedupeArticles } from './recommendation';
const parser = new Parser();
const SOURCES = [
 {id:'universs',label:'UniverRSS',url:'https://universs-xi.vercel.app/api/feeds'},
 {id:'cosmorss',label:'CosmoRSS',url:'https://cosmorss.vercel.app/api/feeds'},
];
const HN='https://hacker-news.firebaseio.com/v0/newstories.json';
function stripHtml(v:string=''){return v.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,420)}
export function classify(title:string,summary:string,source:string):{domain:Domain|null;region:Region;tags:string[]} { const s=`${title} ${summary} ${source}`.toLowerCase(); const tags:string[]=[]; const add=(d:Domain)=>tags.push(d);
 const region:Region=/india|delhi|mumbai|bengaluru|bangalore|hyderabad|chennai|kolkata|modi/.test(s)?'india':/oregon|portland|salem|beaverton|multnomah/.test(s)?'oregon':'global';
 let domain:Domain|null=null; if(/ai|software|developer|programming|data center|amazon|internet|tech|computer|open source/.test(s)) domain='technology'; else if(/science|space|research|physics|biology/.test(s)) domain='science'; else if(/health|medical|medicine|hospital|aca/.test(s)) domain='health'; else if(/climate|environment|energy|lng|weather/.test(s)) domain='environment'; else if(/economy|jobs|market|business|finance/.test(s)) domain='economy'; else if(/politic|trump|congress|election|court/.test(s)) domain='politics'; else if(/war|ukraine|israel|china|international|world/.test(s)) domain='world'; else if(/culture|arts|book|film|music|education/.test(s)) domain='culture'; else if(/security|cyber|privacy/.test(s)) domain='security'; if(domain)add(domain); return {domain,region,tags}; }
const TIME_SENSITIVE_DOMAINS=new Set<Domain>(['politics','world','economy','health','environment','security']);
export function isFresh(article:Pick<Article,'publishedAt'|'domain'|'origin'>,now=new Date()):boolean { if(!article.publishedAt)return false; const published=Date.parse(article.publishedAt); if(!Number.isFinite(published))return false; const ageHours=(now.getTime()-published)/3_600_000; if(ageHours< -2)return false; const maxHours=TIME_SENSITIVE_DOMAINS.has(article.domain)?24:7*24; return ageHours<=maxHours; }
function makeArticle(raw:{title?:string;link?:string;pubDate?:string;contentSnippet?:string;content?:string;source?:string;sourceUrl?:string;category?:string;hn?:any}, origin:string):Article|null { if(!raw.title||!raw.link||!/^https?:\/\//.test(raw.link))return null; const summary=stripHtml(raw.contentSnippet||raw.content||''); const c=classify(raw.title,summary,raw.source||origin); if(!c.domain)return null; return {id:raw.link,title:stripHtml(raw.title),link:raw.link,source:raw.source||origin,sourceUrl:raw.sourceUrl||raw.link,publishedAt:raw.pubDate||null,domain:c.domain,summary,tags:c.tags,region:c.region,quality:1,reasons:[origin==='AllSides / Open RSS'?'balanced-news feed':'source feed'],origin,hn:raw.hn||null}; }
async function fetchJson(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{'user-agent':'epistemic-news/0.1'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json();}
async function fetchRss(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{'user-agent':'epistemic-news/0.1','accept':'application/rss+xml, application/xml'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return parser.parseString(await r.text());}
export async function loadNews():Promise<NewsPayload>{ const statuses:SourceStatus[]=[]; const all:Article[]=[]; const warnings:string[]=[];
 await Promise.all(SOURCES.map(async s=>{try{const data=await fetchJson(s.url); const raw=Array.isArray(data?.items)?data.items:data?.items||[]; all.push(...raw.map((x:any)=>makeArticle({...x,source:x.source||s.label,sourceUrl:x.sourceUrl||s.url},s.label)).filter(Boolean) as Article[]); statuses.push({id:s.id,label:s.label,url:s.url,ok:true,itemCount:raw.length,updatedAt:data?.lastUpdated||new Date().toISOString()});}catch(e){statuses.push({id:s.id,label:s.label,url:s.url,ok:false,itemCount:0,updatedAt:null,error:String(e)});warnings.push(`${s.label} unavailable`);}}));
 try {const xml=await fetchRss('https://openrss.org/feed/www.allsides.com/unbiased-balanced-news'); const rows=xml.items.map(x=>makeArticle({title:x.title,link:x.link,pubDate:x.pubDate,content:x.contentSnippet||x.content,source:'AllSides',sourceUrl:'https://www.allsides.com'},'AllSides / Open RSS')).filter(Boolean) as Article[]; all.push(...rows); if(!statuses.some(s=>s.id==='allsides'))statuses.push({id:'allsides',label:'AllSides / Open RSS',url:'https://openrss.org/feed/www.allsides.com/unbiased-balanced-news',ok:true,itemCount:rows.length,updatedAt:new Date().toISOString()});}catch(e){warnings.push('AllSides unavailable'); statuses.push({id:'allsides',label:'AllSides / Open RSS',url:'https://openrss.org/feed/www.allsides.com/unbiased-balanced-news',ok:false,itemCount:0,updatedAt:null,error:String(e)});}
 try {const ids=await fetchJson(HN); const top=await Promise.all((ids as number[]).slice(0,40).map(id=>fetchJson(`https://hacker-news.firebaseio.com/v0/item/${id}.json`))); const rows=top.map((x:any)=>makeArticle({title:x.title,link:x.url||`https://news.ycombinator.com/item?id=${x.id}`,pubDate:x.time?new Date(x.time*1000).toISOString():undefined,source:'Hacker News',sourceUrl:'https://news.ycombinator.com',hn:{score:x.score||0,comments:x.descendants||0,url:`https://news.ycombinator.com/item?id=${x.id}`}},'Hacker News')).filter(Boolean) as Article[]; all.push(...rows); statuses.push({id:'hn',label:'Hacker News',url:HN,ok:true,itemCount:rows.length,updatedAt:new Date().toISOString()});}catch(e){warnings.push('Hacker News unavailable');}
 const normalized=dedupeArticles(all); const items=normalized.filter(item=>isFresh(item)); const staleCount=normalized.length-items.length; if(staleCount)warnings.push(`${staleCount} stale items excluded from the current edition`); items.sort((a,b)=>(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0)); const coverage:Record<string,number>={}; for(const item of items)coverage[item.domain]=(coverage[item.domain]||0)+1; return {items,sources:statuses.sort((a,b)=>a.label.localeCompare(b.label)),fetchedAt:new Date().toISOString(),warnings,coverage}; }
