import { createHash } from 'node:crypto';
import type { Article, Domain, Region } from './types';
const BASE_URL=process.env.TYPESAFE_BASE_URL||'https://api.typesafe.ai';
const MODEL=process.env.TYPESAFE_DEFAULT_MODEL||'jev-latest';
const topics:Record<string,string>={technology:'Technology, computing, software, AI, hardware and digital products',science:'Scientific research, space, physics, biology and mathematics',health:'Medicine, public health and health policy',economy:'Business, jobs, finance, markets and economic policy',politics:'Government, elections, courts and civic institutions',world:'International affairs, conflict and geopolitics',culture:'Arts, books, music, film, education and society',environment:'Climate, ecology, energy and the natural world'};
const regions:Record<string,string>={portland:'Portland, Oregon local news',oregon:'Oregon statewide news',india:'India, including Indian states and cities',us:'United States outside Oregon',global:'International or geographically broad news'};
const contentTypes:Record<string,string>={breaking:'Breaking or rapidly developing news',current:'Current reported news or a recent development',analysis:'Analysis or interpretation of a current event',explainer:'Background or explanatory material',opinion:'Opinion or commentary',blog:'Personal or independent blog post'};
const sensitivities:Record<string,string>={breaking:'Could become misleading within hours if stale',current:'Relevant mainly within a day or two',evergreen:'Useful for several days or longer'};
export type JevClassification={domain:Domain;region:Region;contentType:string;timeSensitivity:'breaking'|'current'|'evergreen'};
export function parseJevClassification(payload:any):JevClassification|null {const a=payload?.answers||{}; const domain=a.topic?.choice as Domain; const region=a.region?.choice as Region; const contentType=a.content_type?.choice as string; const timeSensitivity=a.time_sensitivity?.choice as JevClassification['timeSensitivity']; if(!topics[domain]||!regions[region]||!contentTypes[contentType]||!sensitivities[timeSensitivity])return null; return {domain,region,contentType,timeSensitivity};}
const cache=new Map<string,JevClassification>();
function key(article:Article){return createHash('sha256').update(`${article.title}\n${article.summary}\n${article.source}`).digest('hex');}
async function classifyOne(article:Article):Promise<JevClassification|null>{const k=key(article);if(cache.has(k))return cache.get(k)!; const response=await fetch(`${BASE_URL}/v1/systemone`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.TYPESAFE_API_KEY||''}`},body:JSON.stringify({model:MODEL,state:{title:article.title,summary:article.summary,source:article.source},questions:{topic:{type:'choice',instructions:'Choose the single best primary topic. Do not use geography as the topic.',criteria:topics},region:{type:'choice',instructions:'Choose the main geographic scope. Choose global if no specific geography dominates.',criteria:regions},content_type:{type:'choice',instructions:'Classify the form of this item.',criteria:contentTypes},time_sensitivity:{type:'choice',instructions:'How quickly does this item become stale?',criteria:sensitivities}}}),signal:AbortSignal.timeout(10000)}); if(!response.ok)throw new Error(`Jev ${response.status}`); const parsed=parseJevClassification(await response.json());if(parsed)cache.set(k,parsed);return parsed;}
export async function classifyWithJev(articles:Article[]):Promise<{items:Article[];usedJev:boolean;failed:number}>{if(!process.env.TYPESAFE_API_KEY)return {items:articles,usedJev:false,failed:0}; let failed=0;let usedJev=false; const items=await mapLimit(articles,8,async article=>{try{const c=await classifyOne(article);if(!c)return article;usedJev=true;return {...article,...c,reasons:[...article.reasons,'Jev classified']};}catch{failed++;return article;}});return {items,usedJev,failed};}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out:R[]=[];let next=0;async function worker(){while(next<items.length){const i=next++;out[i]=await fn(items[i]);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out;}
