'use client';
import {useEffect,useMemo,useState} from 'react';
import type {Article,Feedback,NewsPayload} from '@/lib/types';
import {selectEdition,articleInterestPrediction} from '@/lib/recommendation';
import {brierScore,gatedSkill} from '@/lib/metrics';
import {loadFeedback,saveFeedback,loadSaved,saveSaved,loadNotes,saveNotes} from '@/lib/storage';
import {epistemicGain,domainLabel} from '@/lib/epistemic';

type Tab='today'|'explore'|'interests'|'saved'|'sources';
const empty:NewsPayload={items:[],sources:[],fetchedAt:'',warnings:[],coverage:{}};
export default function NewsApp(){
 const [tab,setTab]=useState<Tab>('today'); const [data,setData]=useState(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [feedback,setFeedback]=useState<Feedback[]>([]); const [saved,setSaved]=useState<Article[]>([]); const [notes,setNotes]=useState<Record<string,string>>({}); const [filter,setFilter]=useState('all');
 const refresh=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/news');if(!r.ok)throw new Error('News sources are unavailable');setData(await r.json())}catch(e){setError(String(e))}finally{setLoading(false)}};
 useEffect(()=>{setFeedback(loadFeedback());setSaved(loadSaved());setNotes(loadNotes());refresh()},[]);
 const edition=useMemo(()=>selectEdition(data.items),[data.items]); const visible=filter==='all'?edition:edition.filter(x=>x.domain===filter); const domains=[...new Set(edition.map(x=>x.domain))];
 const toggleSaved=(a:Article)=>{const next=saved.some(x=>x.id===a.id)?saved.filter(x=>x.id!==a.id):[...saved,a];setSaved(next);saveSaved(next)};
 const rate=(a:Article,subject:Feedback['subject'])=>{const next=feedback.filter(x=>x.articleId!==a.id);next.push({articleId:a.id,subject,timestamp:new Date().toISOString(),prediction:articleInterestPrediction(a,feedback),baselinePrediction:.5});setFeedback(next);saveFeedback(next)};
 const addNote=(a:Article)=>{const note=window.prompt('What became clearer?',notes[a.id]||'');if(note!==null){const next={...notes,[a.id]:note};setNotes(next);saveNotes(next)}};
 return <main className="app"><header><div className="brand"><span className="eyebrow">A calmer reading instrument</span><h1>Epistemic News</h1></div><button className="refresh" onClick={refresh} disabled={loading}>{loading?'Updating…':'Refresh sources'}</button></header><nav className="nav" aria-label="Primary">{(['today','explore','interests','saved','sources'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='interests'?'My interests':x[0].toUpperCase()+x.slice(1)}</button>)}</nav>{error&&<div className="alert">{error}. Saved stories and your profile remain available.</div>}{data.warnings.length>0&&<div className="warning">Partial update: {data.warnings.join(' · ')}</div>}
 {tab==='today'&&<><section className="hero"><div><p className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h2>A finite edition for a wider world.</h2><p className="lede">{edition.length} stories across {domains.length} subjects. No infinite scroll, no click race.</p></div><aside><strong>Coverage</strong><span>{domains.map(domainLabel).join(' · ')||'Waiting for sources'}</span><small>{data.fetchedAt?`Sources checked ${new Date(data.fetchedAt).toLocaleTimeString()}`:''}</small></aside></section><div className="filters"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All</button>{domains.map(d=><button key={d} className={filter===d?'selected':''} onClick={()=>setFilter(d)}>{domainLabel(d)}</button>)}</div><section className="layout"><div className="stories">{loading&&!edition.length?<div className="empty">Gathering your sources…</div>:visible.map(a=><StoryCard key={a.id} article={a} feedback={feedback.find(x=>x.articleId===a.id)} saved={saved.some(x=>x.id===a.id)} onRate={rate} onSave={toggleSaved} onNote={addNote} />)}</div><EditionSidebar data={data} edition={edition}/></section></>}
 {tab==='explore'&&<Explore data={data} onOpen={()=>setTab('today')}/>} {tab==='interests'&&<Interests feedback={feedback} items={data.items}/>} {tab==='saved'&&<section><div className="section-heading"><p className="eyebrow">Your reading list</p><h2>Saved for later</h2></div>{saved.length?<div className="stories">{saved.map(a=><StoryCard key={a.id} article={a} feedback={feedback.find(x=>x.articleId===a.id)} saved onRate={rate} onSave={toggleSaved} onNote={addNote}/>)}</div>:<div className="empty">Nothing saved yet.</div>}</section>} {tab==='sources'&&<Sources data={data}/>}<footer>Epistemic News · Your feedback is yours · No engagement optimization</footer></main>
}
function StoryCard({article:a,feedback:f,saved,onRate,onSave,onNote}:{article:Article;feedback?:Feedback;saved:boolean;onRate:(a:Article,s:Feedback['subject'])=>void;onSave:(a:Article)=>void;onNote:(a:Article)=>void}){return <article className="card"><div className="card-top"><span className="pill">Topic · {domainLabel(a.domain)}</span>{a.region!=='global'&&<span className="region-pill">Region · {a.region==='oregon'?'Portland / Oregon':'India'}</span>}<span>{a.source}</span>{a.hn&&<span>HN {a.hn.score}</span>}</div><h3>{a.title}</h3><p>{a.summary||'Open the original source for the full article.'}</p><div className="meta">{a.source} · {a.publishedAt?new Date(a.publishedAt).toLocaleDateString():'Date unavailable'} · {a.reasons[0]}</div><div className="actions"><a className="read" href={a.link} target="_blank" rel="noreferrer">Read original ↗</a><button onClick={()=>onSave(a)}>{saved?'Saved':'Save'}</button><button onClick={()=>onNote(a)}>Reflect</button></div><div className="feedback"><span>Does this subject interest you?</span><button className={f?.subject==='yes'?'chosen':''} onClick={()=>onRate(a,'yes')}>Yes</button><button className={f?.subject==='no'?'chosen':''} onClick={()=>onRate(a,'no')}>No</button><button className={f?.subject==='unsure'?'chosen':''} onClick={()=>onRate(a,'unsure')}>Unsure</button></div></article>}
function EditionSidebar({data,edition}:{data:NewsPayload;edition:Article[]}){return <aside className="sidebar"><p className="eyebrow">About this edition</p><h3>Broad by design</h3><p>Personal relevance has a budget. Portland/Oregon and India-first stories are protected when suitable inventory exists.</p><div className="coverage">{Object.entries(data.coverage).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div key={k}><span>{domainLabel(k as any)}</span><strong>{v}</strong></div>)}</div><p className="muted">{edition.length<12?'The edition is shorter because suitable material was unavailable.':'The edition stops here by design.'}</p></aside>}
function Explore({data,onOpen}:{data:NewsPayload;onOpen:()=>void}){const groups=Object.entries(data.coverage);return <section><div className="section-heading"><p className="eyebrow">Explore without being profiled</p><h2>Follow a question, not a feed.</h2><p className="lede">Browsing does not change your interest model. Feedback does.</p></div><div className="explore-grid">{groups.map(([domain,count])=><button key={domain} className="explore-card" onClick={onOpen}><span>{domainLabel(domain as any)}</span><strong>{count} available stories</strong><small>Read current reporting and look for a bridge.</small></button>)}</div></section>}
function Interests({feedback,items}:{feedback:Feedback[];items:Article[]}){const rated=feedback.filter(f=>f.subject!=='unsure');const model=rated.map(f=>f.prediction);const outcomes=rated.map(f=>f.subject==='yes'?1:0);const baseline=rated.map(f=>f.baselinePrediction);const skill=gatedSkill(brierScore(model,outcomes),brierScore(baseline,outcomes),rated.length);const domains=[...new Set(items.map(x=>x.domain))];return <section><div className="section-heading"><p className="eyebrow">What the app is learning about you</p><h2>Interest prediction</h2><p className="lede">This measures whether predictions improve—not how much of you the app “understands.”</p></div><div className="metric"><strong>{skill.status==='collecting'?'Collecting evidence':skill.skill===null?'Not measurable':`${(skill.skill*100).toFixed(1)}%`}</strong><span>{skill.status==='collecting'?`${rated.length}/20 rated calibration responses`: 'paired Brier-skill versus the onboarding baseline'}</span></div><div className="interest-grid">{domains.map(d=>{const fs=feedback.filter(f=>items.find(a=>a.id===f.articleId)?.domain===d&&f.subject!=='unsure');const yes=fs.filter(f=>f.subject==='yes').length;const no=fs.filter(f=>f.subject==='no').length;return <div className="interest" key={d}><strong>{domainLabel(d)}</strong><span>{fs.length?`${yes} interested · ${no} not interested`:'Untested—not uninterested'}</span></div>})}</div><div className="advanced"><strong>Measurement notes</strong><p>Predictions were recorded before feedback. Missing and unsure answers do not count. This is a local, single-user descriptive metric; it becomes meaningful only after repeated, broadly sampled responses.</p></div></section>}
function Sources({data}:{data:NewsPayload}){return <section><div className="section-heading"><p className="eyebrow">Source health and coverage</p><h2>Where today came from</h2><p className="lede">The app reports gaps instead of quietly filling them.</p></div><div className="source-list">{data.sources.map(s=><div className="source" key={s.id}><span className={s.ok?'dot ok':'dot'}></span><div><strong>{s.label}</strong><small>{s.ok?`${s.itemCount} items · checked ${s.updatedAt?new Date(s.updatedAt).toLocaleTimeString():'recently'}`:`Unavailable: ${s.error||'unknown error'}`}</small></div></div>)}</div><div className="gap"><strong>Priority coverage</strong><p>Portland/Oregon and India are prioritized. Health, climate, arts, general science and deeper local coverage may still be thin; add feeds rather than assuming absence.</p></div></section>}
